version: 2.1
orbs:
  jq: circleci/jq@3.0.2
  
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - jq/install
      - run:
          name: testing values
          command: echo '<< pipeline.trigger_parameters.webhook.body >>' | sed 's/\\"/"/g' | jq '.action'
      - run:
          name: "Print event action (1)"
          command: |
            EVENT_ACTION=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | sed 's/\\"/"/g' | jq '.action')
            echo "Action is: $EVENT_ACTION"
      
workflows:
  do_some_stuff:
    jobs:
      - myjob
